#!/bin/bash

#Skript väljastab vastavalt kasutaja sisestatud kuu numbrile, mis on (1-12), väljastada kuu nimetuse
#Kui kuu number on suurem kui 12, väljastatakse veateade

echo -n "Sisestage kuu number (1-12 vahemikus): "
read number

if [ $number -ge 1 -a $number -le 12 ]; then
    case $number in
        1) echo "Esimene kuu on jaanuar" ;;
        2) echo "Teine kuu on veebruar" ;;
        3) echo "Kolmas kuu on märts" ;;
        4) echo "Neljas kuu on aprill" ;;
        5) echo "Viies kuu on mai" ;;
        6) echo "Kuues kuu on juuni" ;;
        7) echo "Seitsmes kuu on juuli" ;;
        8) echo "Kaheksas kuu on august" ;;
        9) echo "Uheksas kuu on september" ;;
        10) echo "Kumnes kuu on oktoober" ;;
        11) echo "Uheteistkumnes kuu on november" ;;
        12) echo "Kaheteistkumnes kuu on detsember" ;;
    esac
else
    echo "Sisestatud number ei sobi! Sisestage korrektne kuu number."
fi
