#!/bin/bash

#See rida väljastab teksti, et kasutaja sisestaks oma nime
echo -n "Sisesta oma ees- ja perenimi: "

#See rida küsib kasutaja ees ja perenime
read eesnimi prerenimi

#See rida tervitab kasutajat ja kirjutab tema nime
echo "Tere tulemast, $eesnimi $perenimi"
